# http://www.appveyor.com/docs/appveyor-yml

install:
  - echo This is batch
  
build: off
  
  
test_script:
  - echo This is my custom test script
  - tests\run_tests nopause
  - rem the below unfortunately doesn't work
  - rem ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test_results.xml))  
  - ps: if (-not (select-string -path test_results.xml -pattern "success=""False""") -eq "") { exit 1 }
  
  
