# http://www.appveyor.com/docs/appveyor-yml

install:
  - echo This is batch
  
build: off
  
  
test_script:
  - echo This is my custom test script
  - tests\run_tests nopause
  - ps: $wc = New-Object 'System.Net.WebClient'
  - set
  - echo $APPVEYOR_JOB_ID
  - ps: echo $APPVEYOR_JOB_ID
  - echo %APPVEYOR_JOB_ID%
  - ps: echo %APPVEYOR_JOB_ID%
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$APPVEYOR_JOB_ID", (Resolve-Path .\test_results.xml))  
  
  
